// flow-typed signature: 1534380dc9b38159ef8146da6a77da8d
// flow-typed version: <<STUB>>/circle-timer_v^0.1.5/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'circle-timer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'circle-timer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'circle-timer/circle-timer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'circle-timer/circle-timer.js' {
  declare module.exports: $Exports<'circle-timer/circle-timer'>;
}
